### PR TITLE
Bump to latest GNU toolchain

### PR DESCRIPTION
**Pull request by dpetrisko**
This PR adds support for GCC 13 which introduces the bitmanip extension (which we support)

### CODE REVIEW

**Review by muwyse — APPROVED** [review]
LGTM

Does Linux still boot on ZP?

Side note: I think GIT_SUBMODULE_DEPTH should be turned on by default. I have a change somewhere that does this, so I can submit it separately for discussion.

**Comment by dpetrisko** [comment]
Yep, Linux on ZP is still good with this + dev BP. 

IIRC there was some concern about old git versions for SUBMODULE DEPTH, but I'm fine with enabling it by default

**Comment by muwyse** [comment]
> Yep, Linux on ZP is still good with this + dev BP.

Great! You can merge when ready.

> IIRC there was some concern about old git versions for SUBMODULE DEPTH, but I'm fine with enabling it by default

It is supported since at least 2.16.5, which is 6 years old. I think that qualifies as BP SDK "supports relatively old git versions".

**Comment by dpetrisko** [comment]
Oh how time flies :)

**Pull request merged**
