### PR TITLE
add lean, fast build for panic room

### PR DESCRIPTION
**Pull request by taylor-bsg**
Open to better names to call this!  Useful for getting people up and running with Panic Room running on RTL in all of its forms (ASIC, FPGA, VCS, Verilator).

### CODE REVIEW

**Comment by dpetrisko** [comment]
Hi, are the things this is solving
- --disable-gdb 
- not updating riscv-qemu
- Not building gcc-linux

Anything else this does? I think we should do the first two in our default GCC build and then have the panicroom target basically just do dramfs instead of linux (make sdk will do both dramfs and linux).

**Comment by taylor-bsg** [comment]
Also: does not checkout any other subrepos in this level, does not check out dejagnu inside gnu, do not checkout/build Dromajo, or bedrock (do the docs say what bedrock does inside here?)

**Comment by taylor-bsg** [comment]
Merging, leaving refactoring the general case for later. IMHO, leaving the full build there is useful for when we do want all of these things (gdb, etc); we will not have to reconstruct what is necessary.

**Comment by dpetrisko** [comment]
That’s fine, I can fix it up later.  This is the problem though:

make panicroom 
make gnu 

will rebuild the dramfs toolchain because the gnu tag is separate than the panicroom tag. 

So having
make panicroom 
make gnu-linux 
Where 
gnu: panicroom gnu-linux 

means you could do one or both and it’ll only rebuild what it needs to

**Pull request merged**
