### PR TITLE
Adding linker gen

### PR DESCRIPTION
**Pull request by dpetrisko**

### CODE REVIEW

**Comment by farzamgl** [comment]
What problem does this solve? I mean we still have to edit the param file and rebuild the linker to change those values. Isn't the --defsym approach more versatile?

**Comment by dpetrisko** [comment]
What’s the defsym approach?

My thought here would be so that we would eventually have several platforms to support which may/will have different peripherals and memory maps

**Comment by farzamgl** [comment]
To set it through the gcc flags for each test suite. Are different platforms going to need different linker scripts though? Stuff like stack size is more dependent on the program than the platform.

**Comment by dpetrisko** [comment]
Linker scripts are the primary way to differentiate between platforms. Program segments may be placed in ROM/RAM/FLASH, have size and address differences, etc. 

I see what you’re saying though, changing symbols is useful for things that are different per program e.g. argc / argv. Top of dram / stack I would say is platform dependent more than program. The minimum stack size needed for a program is of course program dependent, but shrinking the maximum stack size to fit it is just an optimization we use to reduce sim time

**Comment by farzamgl** [comment]
I see. So are we going to write a linker script generator for each platform?

**Comment by dpetrisko** [comment]
Probably just add parameters to this one, but whatever ends up being easier

**Pull request merged**
